trigger:
- master

pool:
  vmImage: $(vmImageName)

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: 'sp-acr-rekha'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'sp-rekha-all'
    azureResourceGroup: 'my-aks01'
    kubernetesCluster: 'my-aks01-cluster'
    command: 'apply'
    arguments: '-f deploy.yaml'