trigger:
- master

pool:
  name: Azure Pipelines

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'sp-acr'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'sp-terraform'
    azureResourceGroup: 'my-aks01'
    kubernetesCluster: 'my-aks01-cluster'
    command: 'apply'
    arguments: '-f deploy.yaml'