
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-echo-headers
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: private-reg
  template:
    metadata:
      labels:
        name: private-reg
  spec:
    containers:
    - name: private-reg-container
      image: acr01rekha.azurecr.io/nginx-echo-headers:latest
    imagePullSecrets:
    - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-echo-headers-service
spec: 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-echo-headers

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: nginx-echo-headers-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway 
spec: 
  rules:
  - http:
      paths:
      - backend:
          service: 
            name: nginx-echo-headers-service
            port: 
              number: 80
        path: /
        pathType: Prefix